AMQP_URI: 'amqp://ntjuoyrh:S5mrn6IUnwfzrUaqvPsJ-K60FA9CuFog@skunk.rmq.cloudamqp.com/ntjuoyrh'
WEB_SERVER_ADDRESS: '0.0.0.0:8000'
YOWSUP_USERNAME: '6287834423879'
YOWSUP_PASSWORD: 'zU7Ma/QMlOTRwo5IDTYMKtLmJKk='
TOKEN_RESEND_MESSAGES: 'quiero_que_me_token'
ENDPOINT_RESEND_MESSAGES: 'http://localhost/loquesea'
rpc_exchange: 'nameko-rpc'
max_workers: 1
parent_calls_tracked: 10
